name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        # with: 
        #   repository: '{{github.repository}}'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test